services:
  redis:
    image: redis:latest
    container_name: sse-redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

  sse-service-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sse-service:latest
    container_name: sse-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://host.docker.internal:8761/eureka
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=host.docker.internal:9092
      - SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL=http://host.docker.internal:8081
      - SPRING_DATA_REDIS_HOST=host.docker.internal
      - SPRING_DATA_REDIS_PORT=6380
      - JAVA_OPTS=-Xms512m -Xmx1g
      - EUREKA_INSTANCE_IP_ADDRESS=host.docker.internal
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis


volumes:
  redis-data: