spring:
  application:
    name: sse-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: sse-server
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: http://localhost:8081
      auto.register.schemas: true
springdoc:
  swagger-ui:
    path: /api
room:
  service:
    url: http://localhost:8080
server:
  port: 8084


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka